### PR TITLE
Change LICENSE from LGLP-3.0 to MPL-2.0

### PR DESCRIPTION
**Pull request by maciejhirsz**
Discussion in #32.

@ltfschoen since you've made some changes I must ask: are you okay with this?

CC @ranaya-formant @mbaulch

### CODE REVIEW

**Comment by ltfschoen** [comment]
yes, i'm all for open source too. just to be clear on the requirements, is it sufficient to just add this [MPL-2.0 LICENSE document](https://www.mozilla.org/en-US/MPL/2.0/) in the project root of forks like it's mentioned here 
https://opensource.stackexchange.com/questions/8831/pros-and-cons-of-using-mpl-2-0-license. so in the repo I'm using [here](https://github.com/ltfschoen/kobold-test/blob/master/LICENSE) I'd just replace the GPL-2.0 LICENSE file with the MPL-2.0 one

**Comment by maciejhirsz** [comment]
> is it sufficient to just add this [MPL-2.0 LICENSE document](https://www.mozilla.org/en-US/MPL/2.0/) in the project root of forks like it's mentioned here

Technically yes if you have a `LICENSE` file.

The text of the license comes with a notice that's intended to be put in source code:
```text
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
```
Though that notice itself is technically optional, per:
> If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.

Now that you mentioned it, I will add it to the files just to be prudent.

**Comment by ltfschoen** [comment]
i had a read of the license and have a weird question (I'm not well verses on legal documents). if for example someone forked this repo and made some changes but then they died and github suspended their account for being inactive such that their fork was no longer open-source (or they didn't die, but their github account was suspended, and causing their fork to not be publicly available) then could that still warrant a notice of non-compliance with the MPL-2.0 License
being send to the contributor, and litigation being braught against them if they didn't make the code open-source code again so they'd be compliant again prior to 30 days after their receipt of the notice? it might be easier to comply with MPL-2.0 if forks of the code base were moved onto a decentralised git version control host?

**Comment by maciejhirsz** [comment]
IANAL and this is obviously not a legal advice but I believe LICENSE would only be violated if you _distrubted_ a modified closed-source fork of Kobold, or _distributed_ an app using a modified close-source fork of Kobold. Just the modified code existing somewhere shouldn't be a problem, and in this particular case for anything to happen I would have to know about it to begin with and take action.

Also not really sure how you'd litigate against someone dead :sweat_smile:.

**Pull request merged**
